name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: aiplan4eu/upf

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mypy check
        uses: jpetrucciani/mypy-check@master

      - name: Checkout Tamer UPF
        uses: actions/checkout@v2
        with:
            repository: aiplan4eu/tamer-upf
            path: tamer-upf

      - run: bash tamer-upf/install.sh

      - run: bash run_tests.sh
