name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: aiplan4eu/upf

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mypy check
        uses: jpetrucciani/mypy-check@master

      - name: Checkout Tamer UPF
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/tamer-upf
          path: tamer-upf

      - name: Install Tamer UPF
        run: bash tamer-upf/install.sh

      - name: Run tests
        run: bash run_tests.sh

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true



name: Deploy Wiki

on:
  push:
    paths:
      # Trigger only when docs/wiki directory changes
      - 'docs/wiki/**'
    branches:
      # And only on master branch
      - master

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync
        # WIKI_DIR's default is wiki/
        WIKI_DIR: docs/wiki/
        GH_TOKEN: ${{ secrets.WIKI_GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.WIKI_COMMITTER_EMAIL }}
        GH_NAME: ${{ secrets.WIKI_COMMITTER_NAME }}