name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: aiplan4eu/upf

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mypy check
        uses: jpetrucciani/mypy-check@master

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install Development Python dependencies
        run: python3 -m pip install -r dev-requirements.txt

      - name: Checkout Tamer UPF
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/tamer-upf
          path: tamer-upf
          ref: "5786e4078d9bd1b358920a483712e52b452996fc"

      - name: Install Tamer UPF
        run: python3 -m pip install tamer-upf

      - name: Checkout Pyperplan UPF
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/pyperplan-upf
          path: pyperplan-upf
          ref: "4b66bc1764ff710bdcbda285f93ee15f53129e4e"

      - name: Install Pyperplan UPF
        run: python3 -m pip install pyperplan-upf

      - name: Download ENHSP
        run: |
          git clone https://gitlab.com/enricos83/ENHSP-Public.git
          cd ENHSP-Public; git checkout enhsp-20; ./compile; cd ..
          mkdir .planners; mv ENHSP-Public/enhsp-dist .planners/enhsp-20; rm -rf ENHSP-Public

      - name: Run tests
        run: bash run_tests.sh

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
