name: CI

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: aiplan4eu/unified-planning

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install Development Python dependencies
        run: python3 -m pip install -r dev-requirements.txt

      - name: MyPy check
        run: |
          python3 -m mypy --version
          python3 -m mypy unified_planning

      - name: Checkout Tamer unified-planning interface
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-tamer
          path: up-tamer
          ref: "5180ab37110a3de480d685980aa50802a5ec96b2"

      - name: Install Tamer unified-planning interface
        run: python3 -m pip install up-tamer/

      - name: Checkout Pyperplan unified-planning interface
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-pyperplan
          path: up-pyperplan
          ref: "b161db9bc89e8f204c82511d3b01298b9c170e6b"

      - name: Install Pyperplan unified-planning interface
        run: python3 -m pip install up-pyperplan/

      - name: Download ENHSP
        run: |
          git clone https://gitlab.com/enricos83/ENHSP-Public.git
          cd ENHSP-Public; git checkout enhsp-20; ./compile; cd ..
          mkdir .planners; mv ENHSP-Public/enhsp-dist .planners/enhsp-20; rm -rf ENHSP-Public

      - name: Run tests
        run: bash run_tests.sh

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true


  run-tests-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Checkout Pyperplan unified-planning interface
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-pyperplan
          path: up-pyperplan
          ref: "b161db9bc89e8f204c82511d3b01298b9c170e6b"

      - name: Install Pyperplan unified-planning interface
        run: python3 -m pip install up-pyperplan/

      - name: Run tests
        run: |
          python3 -m pip install pytest
          python3 -m pytest unified_planning/test


  deploy-pypi:
    runs-on: ubuntu-latest
    needs: run-tests # We only deploy if the tests were successful
    if: github.ref == 'refs/heads/master' # We only deploy on master commits

    steps:
    - name: Checkout repo
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Make distrib
      run: |
        python3 -m pip install wheel
        bash make_distrib.sh

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}