name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: aiplan4eu/upf

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mypy check
        uses: jpetrucciani/mypy-check@master

      - name: Checkout Tamer UPF
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/tamer-upf
          path: tamer-upf

      - name: Install Tamer UPF
        run: bash tamer-upf/install.sh

      - name: Run tests
        run: |
          python3 -mpip install pytest-cov
          bash run_tests.sh

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true